a: a.cc
	g++ -o a -g -std=c++11 -I${HOME}/lab/casablanca/Release/include -I${HOME}/lab/casablanca/Release/include/cpprest -I${HOME}/lab/casablanca/Release/include/pplx -L${HOME}/lab/casablanca/Binaries/Debug64 a.cc -L/opt/local/lib -lcasablanca -lboost_system-mt
